### ISSUE TITLE
Sample SLURM script for NaCl looks for Python 2.7 (and has a typo)

### ISSUE THREAD

**Issue by jdrusso** [westpa/westpa_tutorials#29]
https://github.com/westpa/westpa_tutorials/blob/26c4c37b4844296faed2a00942db95e0de0aa5ed/tutorial7.1-basic-nacl/runwe.slurm#L18

There's a typo in the sample `runwe.slurm` script where it looks for python 2.7. Additionally, it looks for python 2.7, which probably isn't intended any more.

[Searching the tutorials](https://github.com/search?q=repo%3Awestpa%2Fwestpa_tutorials%20python2.7&type=code) seems to show this in a few places.

According to @jeremyleung521 on the user group, this is a legacy variable that isn't used any more. If that's the case, we should probably just remove it. (Even if it's harmless, if I came across that without knowing this, I'd assume either some incompatibility with python3, or an outdated tutorial.)

Thanks to Fernando Amrein on the WESTPA user group for catching this!

**Comment by jeremyleung521** [comment]
All done!
