### ISSUE TITLE
h5py=2.6 is incompatible with westpa-2017.10-py27_0

### ISSUE THREAD

**Issue by jbarnoud** [westpa/westpa_tutorials#3]
The "advanced_WExplore" tutorial ask to install "h5py=2.6" as a dependency of the WESTA-WExplore plugin (section 6.4.3). However, `conda install h5py=2.6` or `conda install -c conda-forge h5py=2.6` leads to the `westpa-2017.10-py27_0` packaged to be removed.

**Comment by alexrd** [comment]
Thanks for writing.  I can't replicate this problem.  Can you be more specific?  How do you know the package was removed?

**Comment by jbarnoud** [comment]
From the top of my head, I installed westpa with :conda create -n westpa -c conda-forge python=2.7 westpa conda activate westpaconda install h5py=2.6Here the summary warns that westpa will be removed. Le 19 juil. 2019 16:16, Alex Dickson <notifications@github.com> a écrit :Thanks for writing.  I can't replicate this problem.  Can you be more specific?  How do you know the package was removed?

**Comment by atbogetti** [comment]
This issue has been updated in our LiveCoMS manuscript.
